import type { Metadata } from "next";
import { Inter, Germania_One, Amiko } from "next/font/google";
import "./globals.css";
import Footer from "../../../coursera/src/components/footer/Footer";
import NoSessionNavbar from "@/components/navbar/NoSessionNavbar";
import { validateRequest } from "@/auth";
import SessionNavbar from "../../../coursera/src/components/navbar/SessionNavbar";
import { Sidebar } from "@/components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });
const germaniaOne = Germania_One({ subsets: ["latin"], weight: "400" });
const amiko = Amiko({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const { session, user } = await validateRequest();

  return (
    <html lang="en">
      <body className={amiko.className}>
        <div className="relative">
          <Sidebar />
          <div className="w-full fixed top-0 z-10 bg-[#ffffff]">
            {!session && <NoSessionNavbar />}
            {session && <SessionNavbar />}
          </div>
          <div className="pt-[60px] pl-20 pb-[60px]">{children}</div>
            <Footer />
        </div>
      </body>
    </html>
  );
}
