import type { Metadata } from "next";
import { Inter, Germania_One, Amiko } from "next/font/google";
import "./globals.css";
import Footer from "../../../coursera/src/components/footer/Footer";
import NoSessionNavbar from "@/components/navbar/NoSessionNavbar";
import { validateRequest } from "@/auth";
import { NoSessionSidebar } from "@/components/Sidebar/Sidebar";
import RecoilWrapper from "./recoilWrapper";
import { SessionSidebar } from "@/components/SessionSidebar/SessionSidebar";
import { SessionNavbarSSR } from "@/components/navbar/SessionNavbarSSR";
import { Haze } from "@/components/Haze/Haze";
import { Modal } from "@/components/Modal/Modal";
import { DBError } from "@/components/DBError/DBError";

const inter = Inter({ subsets: ["latin"] });
const germaniaOne = Germania_One({ subsets: ["latin"], weight: "400" });
const amiko = Amiko({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Skillcraft",
  description: "Generated by create next app",
  assets: "/logo-no-background.png",
  icons: ["/rocket.svg"],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const { session, user } = await validateRequest();

  return (
    <html lang="en">
      <RecoilWrapper>
        <body className={amiko.className}>
          <div className="relative">
            <div className="w-full fixed top-0 z-10 bg-[#ffffff]">
              {!session && <NoSessionNavbar />}
              {session && <SessionNavbarSSR />}
            </div>
            <div>
              {!session && <NoSessionSidebar />}
              {session && <SessionSidebar />}
            </div>
            <DBError>
              <div className="xl:pt-[82px] pt-[62px] md:pt-[72px] xl:px-4 px-2 ">
                {children}
              </div>
            </DBError>
            <Modal session={session} user={user} />
            <Haze />
            {<div className="mt-16 border-t">
              <Footer />
            </div>}
          </div>
        </body>
      </RecoilWrapper>
    </html>
  );
}
