name: Deploy

on:
  push:
    paths:
      - "apps/**"
      - "packages/**"
      - "deploy.sh"
      - "stripe_login.sh"
      - ".github/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 #The actions/checkout@v2 step is an action provided by GitHub that performs a Git checkout operation. During this step, the runner (github machine) connects to your repository and downloads/clones a copy of your repository code at the specified branch or commit.

      - name: Retrieve Host Key
        run: |
          ssh-keyscan ec2-3-68-90-164.eu-central-1.compute.amazonaws.com > known_hosts

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          chmod 600 keyfile
          mkdir -p ~/.ssh
          cp known_hosts ~/.ssh/known_hosts
          ssh -t -i keyfile ubuntu@ec2-3-68-90-164.eu-central-1.compute.amazonaws.com "
          cd ~/Skillcraft
          git pull origin main
          bash deploy.sh
          "
